name: Build LineageOS ROM

on:
  workflow_dispatch:

jobs:
  build-lineageos:
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Check if sender is repository owner
        if: github.event.repository.owner.login == github.event.sender.login
        run: echo "Sender is the repository owner"
      - name: Not the repository owner
        if: github.event.repository.owner.login != github.event.sender.login
        run: |
          echo "Sender is not the repository owner"
          exit 1



      - name: Initialize workspace
        run: |
          mkdir workspace
          cd workspace
          echo "workspace-folder=$(pwd)" >> $GITHUB_OUTPUT
        id: pwd

      - name: Prepare the build environment
        run: |
          sudo apt install git aria2 -y
          export JAVA_HOME=$(readlink -f $(which java))
          git clone https://gitlab.com/OrangeFox/misc/scripts
          cd scripts
          sudo bash setup/android_build_env.sh
          sed -i 's/cd -/cd ../g' setup/install_android_sdk.sh
          sudo bash setup/install_android_sdk.sh
          mkdir ${{ steps.pwd.outputs.workspace-folder }}/ccache
          export USE_CCACHE=1
          export CCACHE_DIR=${{ steps.pwd.outputs.workspace-folder }}/ccache/
          ccache -M 50G
        working-directory: ${{ steps.pwd.outputs.workspace-folder }}

      - name: Define Constants
        run: |
          # Değişkenleri burada tanımlıyoruz
          export SYNC_URL="https://github.com/LineageOS/android.git"
          export MANIFEST_BRANCH="lineage-15.1"
          export DEVICE_TREE_URL="https://github.com/Camgobeg/device_alps_redwood.git"
          export DEVICE_TREE_BRANCH="full_redwood-user-8.0.0-O00623-1556208356-test-keys"
          export DEVICE_PATH="device/sony/redwood"
          export VENDOR_TREE_URL="https://github.com/AndroidBlobs/vendor_alps_redwood.git"
          export VENDOR_TREE_BRANCH="full_redwood-user-8.0.0-O00623-1556208356-test-keys"
          export VENDOR_PATH="vendor/alps/redwood"
          export KERNEL_TREE_URL="https://github.com/SonyMTKDev/android_kernel_sony_mt6757.git"
          export KERNEL_TREE_BRANCH="lineage-15.1"
          export KERNEL_PATH="kernel/sony/mt6757"
          export DEVICE_NAME="redwood"
          export MAKEFILE_NAME="lineage_redwood"
        id: constants

      - name: Clone and sync Lineage sources
        run: |
          cd ${{ steps.pwd.outputs.workspace-folder }}
          mkdir lineage
          cd lineage
          repo init -u ${{ steps.constants.outputs.SYNC_URL }} -b ${{ steps.constants.outputs.MANIFEST_BRANCH }} --git-lfs
          repo sync
        working-directory: ${{ steps.pwd.outputs.workspace-folder }}

      - name: Clone device tree
        run: |
          cd ${{ steps.pwd.outputs.workspace-folder }}/lineage/
          git clone ${{ steps.constants.outputs.DEVICE_TREE_URL }} -b ${{ steps.constants.outputs.DEVICE_TREE_BRANCH }} ./${{ steps.constants.outputs.DEVICE_PATH }}
        working-directory: ${{ steps.pwd.outputs.workspace-folder }}

      - name: Clone vendor tree
        run: |
          cd ${{ steps.pwd.outputs.workspace-folder }}/lineage/
          git clone ${{ steps.constants.outputs.VENDOR_TREE_URL }} -b ${{ steps.constants.outputs.VENDOR_TREE_BRANCH }} ./${{ steps.constants.outputs.VENDOR_PATH }}
        working-directory: ${{ steps.pwd.outputs.workspace-folder }}

      - name: Clone kernel tree
        run: |
          cd ${{ steps.pwd.outputs.workspace-folder }}/lineage/
          git clone ${{ steps.constants.outputs.KERNEL_TREE_URL }} -b ${{ steps.constants.outputs.KERNEL_TREE_BRANCH }} ./${{ steps.constants.outputs.KERNEL_PATH }}
        working-directory: ${{ steps.pwd.outputs.workspace-folder }}

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 12

      - name: Build Lineage ROM
        run: |
          cd ${{ steps.pwd.outputs.workspace-folder }}/lineage/
          . build/envsetup.sh
          export USE_CCACHE=1
          export CCACHE_DIR=ccache/
          ccache -M 50G
          lunch ${{ steps.constants.outputs.MAKEFILE_NAME }}
          m otapackage
        working-directory: ${{ steps.pwd.outputs.workspace-folder }}
        continue-on-error: true

      - name: Check the output directory before uploading
        run: |
          ls -al ${{ steps.pwd.outputs.workspace-folder }}/lineage/out/target/product/
          echo
          ls -al ${{ steps.pwd.outputs.workspace-folder }}/lineage/out/target/product/${{ steps.constants.outputs.DEVICE_NAME }}/

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.pwd.outputs.workspace-folder }}/lineage/out/target/product/${{ steps.constants.outputs.DEVICE_NAME }}/*.zip
          name: ${{ steps.constants.outputs.DEVICE_NAME }}-${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body: |
            Manifest: ${{ steps.constants.outputs.MANIFEST_BRANCH }}
            Device: ${{ steps.constants.outputs.DEVICE_NAME }}
            Target: ${{ github.event.inputs.BUILD_TARGET }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
